import { Project } from "@/types";

export const projects: Project[] = [
    {
        id: "1",
        title: "gnote更新ツール",
        description: "自社SaaSのgnoteを効率的に更新するためのChrome拡張機能。入力の自動補完や一括更新機能を提供。",
        longDescription: "gnoteの入力作業を大幅に効率化するChrome拡張機能です。フォームの自動補完、テンプレート機能、一括更新機能などを備え、日々の更新作業を数クリックで完了できます。社内で広く利用され、作業時間の大幅な削減に貢献しています。",
        category: "Chrome拡張",
        imageUrl: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?q=80&w=2000&auto=format&fit=crop",
        technologies: ["JavaScript", "Chrome Extension API", "HTML", "CSS"],
        featured: true,
        completionDate: "2024年4月",
        savedHours: 150,
        steps: [
            {
                type: "image",
                url: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?q=80&w=2000&auto=format&fit=crop",
                title: "拡張機能を起動",
                description: "Chrome右上の拡張機能アイコンをクリックして、gnote更新ツールを起動します。",
            },
            {
                type: "image",
                url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=2000&auto=format&fit=crop",
                title: "更新内容を入力",
                description: "ポップアップが表示されたら、更新したい内容をフォームに入力します。テンプレートから選択することも可能です。",
            },
            {
                type: "image",
                url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=2000&auto=format&fit=crop",
                title: "一括更新を実行",
                description: "「更新」ボタンをクリックすると、gnoteに自動でデータが反映されます。複数項目の一括更新にも対応。",
            },
        ],
    },
    {
        id: "2",
        title: "Chatworkメッセージ集約ツール",
        description: "Chatworkのメッセージを自動でスプレッドシートにまとめるGASツール。定期レポート作成に活用。",
        longDescription: "Chatworkの特定ルームのメッセージを自動的に取得し、Googleスプレッドシートに整理・保存するGoogle Apps Scriptです。日次・週次でのレポート作成を自動化し、コミュニケーション履歴の分析やナレッジ蓄積に活用できます。",
        category: "GAS",
        imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2000&auto=format&fit=crop",
        technologies: ["Google Apps Script", "Chatwork API", "Google Sheets"],
        featured: true,
        completionDate: "2024年6月",
        savedHours: 120,
        steps: [
            {
                type: "image",
                url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2000&auto=format&fit=crop",
                title: "スプレッドシートを開く",
                description: "対象のGoogleスプレッドシートを開き、メニューから「拡張機能」→「スクリプト」を選択します。",
            },
            {
                type: "image",
                url: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?q=80&w=2000&auto=format&fit=crop",
                title: "取得設定を行う",
                description: "取得したいChatworkルームIDと期間を設定します。APIトークンは初回のみ設定が必要です。",
            },
            {
                type: "image",
                url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=2000&auto=format&fit=crop",
                title: "メッセージを取得",
                description: "「実行」ボタンをクリックすると、Chatworkからメッセージを取得してスプレッドシートに自動で整理されます。",
            },
            {
                type: "video",
                url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
                title: "使い方動画",
                description: "詳しい使い方は動画でも解説しています。初めて使う方はこちらをご覧ください。",
            },
        ],
    },
    {
        id: "3",
        title: "口コミ収集自動化ツール",
        description: "ECサイトの口コミを自動で取得・分析するスクリプト。マーケティング施策の改善に活用。",
        longDescription: "Amazon、楽天などのECサイトから商品レビューを自動収集し、CSVで出力するツールです。定期実行により最新の口コミを継続的に取得でき、顧客の声を迅速にマーケティング施策に反映できます。",
        category: "自動化ツール",
        imageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=2000&auto=format&fit=crop",
        technologies: ["Python", "Playwright", "Pandas", "CSV"],
        featured: true,
        completionDate: "2024年8月",
        savedHours: 80,
    },
    {
        id: "4",
        title: "社内タスク管理ダッシュボード",
        description: "部署横断でタスクの進捗を可視化するWebダッシュボード。プロジェクト管理の効率化に貢献。",
        longDescription: "複数のプロジェクトやタスクの進捗状況をリアルタイムで可視化するダッシュボードです。スプレッドシートと連携し、チーム全体の作業状況を一目で把握できます。",
        category: "Webアプリ",
        imageUrl: "https://images.unsplash.com/photo-1531403009284-440f080d1e12?q=80&w=2000&auto=format&fit=crop",
        technologies: ["Next.js", "React", "Tailwind CSS", "Google Sheets API"],
        featured: false,
        completionDate: "2024年10月",
        savedHours: 100,
    },
    {
        id: "5",
        title: "定型メール自動送信ツール",
        description: "条件に応じた定型メールを自動送信するGASツール。フォローアップ業務を効率化。",
        longDescription: "スプレッドシートの条件に基づいて、適切なタイミングで定型メールを自動送信するGoogle Apps Scriptです。フォローアップメールやリマインダーの送信を自動化し、業務の抜け漏れを防ぎます。",
        category: "GAS",
        imageUrl: "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?q=80&w=2000&auto=format&fit=crop",
        technologies: ["Google Apps Script", "Gmail API", "Google Sheets"],
        featured: false,
        completionDate: "2024年3月",
        savedHours: 60,
    },
];
