import { Project } from "@/types";

// savedHours は年間の削減時間
// impactAmount は売上・インパクト金額（円）
export const projects: Project[] = [
    {
        id: "1",
        title: "AI事業部のポートフォリオ",
        description: "AI事業部が開発した業務効率化ツールの事例集サイトです。各プロジェクトで「どんな課題を解決したか」「どれだけ時間を削減できたか」を分かりやすく紹介しています。",
        longDescription: "AI事業部が開発した業務効率化ツールの事例集サイトです。各プロジェクトで「どんな課題を解決したか」「どれだけ時間を削減できたか」を分かりやすく紹介しています。",
        features: [
            "プロジェクト一覧の表示",
            "各プロジェクトの詳細ページ（使い方ガイド付き）",
            "スマートフォン・タブレットでも閲覧可能",
        ],
        tags: ["Webアプリ"],
        imageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=2000&auto=format&fit=crop",
        technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
        featured: false,
    },
    {
        id: "2",
        title: "インバウンドコール分析",
        description: "カイクラから通話履歴を自動でダウンロードし、AIが音声を解析するツールです。これまで手が付けられなかった大量の通録データを、初めて分析できるようになりました。",
        longDescription: "カイクラから通話履歴を自動でダウンロードし、AIが音声を解析するツールです。これまで手が付けられなかった大量の通録データを、初めて分析できるようになりました。",
        problem: "コールセンターの通話録音（通録）データが大量にあるが、これまで分析したことがなかった。カイクラ（通録システム）からの手動ダウンロードも時間がかかり、分析の前段階で止まっていた。",
        features: [
            "通録履歴の自動一括ダウンロード（ページ送りも自動対応）",
            "AIによる音声の文字起こし・要約",
            "顧客の感情分析・キーワード抽出",
        ],
        tags: ["LLM（生成AI）", "GAS", "Chrome拡張"],
        imageUrl: "/images/inbound-call-analysis.png",
        technologies: ["Google Apps Script", "Chrome拡張機能", "Google Gemini"],
        featured: true,
        impactAmount: 520000,
        impactLabel: "売上（単発受注）",
        steps: [
            {
                type: "image",
                url: "/images/inbound-call-analysis.png",
                title: "エグゼクティブサマリー",
                description: "AIが通話内容を分析し、応答率・平均通話時間・顧客満足度などの重要指標をサマリーとして出力します。",
            },
            {
                type: "image",
                url: "/images/inbound-call-analysis-2.png",
                title: "詳細分析",
                description: "曜日別・時間帯別のコール数、問い合わせの多いクライアント、主な問い合わせ内容の傾向を可視化します。",
            },
            {
                type: "image",
                url: "/images/inbound-call-analysis-3.png",
                title: "感情・満足度分析",
                description: "音声解析から感情レベル・満足度を数値化。高満足度・中満足度の具体事例と、インサイトに基づくアクションプランを提示します。",
            },
        ],
    },
    {
        id: "3",
        title: "Chatwork問い合わせ一元管理",
        description: "Chatworkの複数ルームに届く問い合わせを、スプレッドシートで一元管理できるようにしたツールです。既読/未読に関係なく全メッセージが記録されるため見落としがなくなり、プランナーへのエスカレーションもボタン一つで実行できます。",
        longDescription: "Chatworkの複数ルームに届く問い合わせを、スプレッドシートで一元管理できるようにしたツールです。既読/未読に関係なく全メッセージが記録されるため見落としがなくなり、プランナーへのエスカレーションもボタン一つで実行できます。",
        problem: "社内のサポートセンターが1つのChatworkアカウントを共有して使っていたため、誰かが未読メッセージを見ると既読になってしまい、他のスタッフが見落とすことがあった。また、プランナーへのエスカレーション連絡も手作業で手間がかかっていた。",
        features: [
            "複数ルームの問い合わせをスプレッドシートに自動記録",
            "既読/未読に関係なく全メッセージを確実に管理",
            "宛先による自動分類（gnote関連 / WEB関連）",
            "プランナーへのエスカレーションをボタン一つで実行",
        ],
        tags: ["GAS"],
        imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2000&auto=format&fit=crop",
        technologies: ["Google Apps Script", "Chatwork API", "Google Sheets"],
        featured: true,
        savedHours: 100,
    },
    {
        id: "4",
        title: "gnote入庫実績レポート",
        description: "gnoteの入庫実績データをBigQueryで完全自動化し、レポートを1つに集約したシステムです。RPAの稼働時間を大幅に削減。約400個あったLooker Studioが1つになりました。",
        longDescription: "gnoteの入庫実績データをBigQueryで完全自動化し、レポートを1つに集約したシステムです。RPAの稼働時間を大幅に削減。パラメーターで出し分けできるようになったため、約400個あったLooker Studioが1つに。全クライアント分の見せ方を一気に変更したり、新規クライアント対応、店舗の追加・削除などの修正・更新も簡単になりました。",
        problem: "RPAでクライアントごとにCSVをダウンロードし、スプレッドシートで集計、Looker Studioに反映という流れで作業していた。定期的に大量のクライアントの作業をしていたため、RPAの稼働時間を大量に使っていた。また、Looker Studioもクライアントごとに作成していたため約400個も存在し、修正・管理が大変だった。",
        features: [
            "RPAによるCSVダウンロード・集計作業を完全自動化",
            "RPAの稼働時間を大幅削減",
            "約400個のレポートを1つに集約（パラメーターで出し分け）",
            "全クライアント分の見せ方変更、新規クライアント対応、店舗の追加・削除が簡単に",
        ],
        tags: ["BigQuery", "GAS"],
        imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2000&auto=format&fit=crop",
        technologies: ["Google BigQuery", "Looker Studio", "Google Apps Script"],
        featured: true,
        impactAmount: 500000,
        impactLabel: "年間インパクト",
    },
    {
        id: "5",
        title: "gnoteコール結果レポート",
        description: "gnoteのコール結果データをBigQueryで自動化し、自作HTMLで柔軟かつグラフィカルなレポートを実現したシステムです。店舗別・エリア別など今まで見れなかった切り口での分析が可能に。",
        longDescription: "gnoteのコール結果データをBigQueryで自動化し、自作HTMLで柔軟かつグラフィカルなレポートを実現したシステムです。見栄えが一気に改善され、店舗別・エリア別など今まで見れなかった切り口での分析が可能に。パラメーターで出し分けているので、全クライアントに対して見せ方を変更したり、新しいグラフを追加したりも一気にできます。",
        problem: "gnoteから手作業でCSVをダウンロードする必要があった。コール結果レポートはLooker Studioすらなく、スプレッドシートのテーブルを見せているだけだった。店舗別やエリア別などの切り口での分析ができなかった。",
        features: [
            "gnoteからのCSVダウンロード・集計を完全自動化",
            "自作HTMLによるグラフィカルなレポート表示",
            "店舗別・エリア別など様々な切り口での分析",
            "全クライアントへの見せ方変更・新しいグラフ追加も一気に対応",
        ],
        tags: ["BigQuery", "GAS"],
        imageUrl: "/images/gnote-call-result-report.png",
        technologies: ["Google BigQuery", "自作HTML", "Google Apps Script"],
        featured: false,
        impactAmount: 250000,
        impactLabel: "年間インパクト",
        steps: [
            {
                type: "image",
                url: "/images/gnote-call-result-report.png",
                title: "コール結果ダッシュボード",
                description: "つながり率、入庫数、コール費用などの主要KPIをグラフ付きで一目で把握。店舗別・ステータス別の分析も可能です。",
            },
            {
                type: "image",
                url: "/images/gnote-call-result-report-2.png",
                title: "エリア/店舗別・ステータス別分析",
                description: "エリア・店舗別の入庫率や、ステータスごとに「その後入庫になった件数」を追跡。どの店舗が成果を出しているか、どのステータスが入庫につながりやすいかが一目でわかります。",
            },
            {
                type: "image",
                url: "/images/gnote-call-result-report-3.png",
                title: "月別推移・詳細データ",
                description: "月別推移グラフで前年同期との比較が可能。期間も自由に変更でき、コール結果詳細テーブルで全ての数値を確認できます。気になった箇所はすべて数値で深掘りできます。",
            },
        ],
    },
    {
        id: "6",
        title: "gnote LINE・アプリレポート",
        description: "gnoteと連携したLINE・アプリ経由の予約データをBigQueryで自動化し、自作HTMLで柔軟にレポート化するシステムです。RPAの稼働時間を削減できました。",
        longDescription: "gnoteと連携したLINE・アプリ経由の予約データをBigQueryで自動化し、自作HTMLで柔軟にレポート化するシステムです。RPAの稼働時間を削減できました。",
        problem: "gnoteからCSVをダウンロードする必要があった。RPAを使っていたため、RPAの稼働時間を使っていた。デジタルチャネルの効果測定が難しかった。",
        features: [
            "gnoteからのCSVダウンロード・集計を完全自動化",
            "RPAの稼働時間を削減",
            "自作HTMLによる柔軟なレポート表示",
            "LINE・アプリ経由の予約データ分析",
        ],
        tags: ["BigQuery", "GAS"],
        imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2000&auto=format&fit=crop",
        technologies: ["Google BigQuery", "自作HTML", "Google Apps Script"],
        featured: false,
        impactAmount: 150000,
        impactLabel: "年間インパクト",
    },
    {
        id: "7",
        title: "gnote Direct（画面操作でデータ抽出）",
        description: "画面上で項目を選択するだけでBigQueryのSQLが実行され、データを抽出できるシステムです。従来のCSVやgnote画面では見れなかった数値が一発で出せるようになりました。",
        longDescription: "画面上で項目を選択するだけでBigQueryのSQLが実行され、データを抽出できるシステムです。従来のCSVやgnote画面では見れなかった数値が一発で出せるようになり、エンプラで10回以上必要だった作業が1回で完了するようになりました。",
        problem: "CSVを見るだけやgnoteの画面だけではわからない数値があり、CSVをダウンロードして手作業でスプレッドシートで集計を毎月する必要があった。また、エンタープライズ版では同じ作業を10回以上繰り返す必要があり、非常に手間がかかっていた。",
        features: [
            "画面上で項目を選択してデータ抽出",
            "従来のCSVやgnote画面では見れなかった数値も一発で取得",
            "エンプラでの繰り返し作業を1回に集約",
            "BigQueryからの柔軟なデータ取得",
        ],
        tags: ["BigQuery", "Webアプリ"],
        imageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=2000&auto=format&fit=crop",
        technologies: ["Python", "Google BigQuery", "Cloud Run"],
        featured: false,
        impactAmount: 100000,
        impactLabel: "年間インパクト",
    },
    {
        id: "8",
        title: "gnoteコール入力支援・優先度判定",
        description: "gnoteのコール画面に便利機能を追加するChrome拡張機能セットです。複数台保有の顧客でも「どの車から案内すべきか」を自動判定。お客様の回答に応じてヒアリングすべき内容が表示されます。",
        longDescription: "gnoteのコール画面に便利機能を追加するChrome拡張機能セットです。複数台保有の顧客でも「どの車から案内すべきか」を自動判定。お客様の回答に応じてヒアリングすべき内容が表示され、選択するだけでgnoteのステータス・コメントが自動で反映されます。一等書記官への検索もボタン一つで実行できます。",
        problem: "クライアントの自社コールセンターで、複数台所有している顧客がいた場合に「どの車から案内すべきか」を判断するために色々なところを見る必要があり、難しいし大変だった。また、お客様の回答に応じたヒアリング内容を手動で選択・入力する必要があり、時間がかかっていた。一等書記官（WEB版車両履歴検索システム）での検索も手作業で面倒だった。",
        features: [
            "コール優先度判定：複数台保有の顧客でも「どの車から案内すべきか」を自動判定",
            "車検満了日・案内すべき内容から優先度を判定",
            "お客様の回答に応じてヒアリングすべき内容を自動表示",
            "選択するだけでgnoteのステータス・コメントが自動反映",
            "一等書記官連携：顧客名・ナンバー・車台番号での検索をボタン一つで実行",
        ],
        tags: ["Chrome拡張", "GAS"],
        imageUrl: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?q=80&w=2000&auto=format&fit=crop",
        technologies: ["Chrome拡張機能", "JavaScript", "Google Apps Script"],
        featured: true,
        impactAmount: 1200000,
        impactLabel: "売上（月額10万円）",
    },
    {
        id: "9",
        title: "gnoteコール・DMリスト自動反映",
        description: "kintoneの設定内容をGASで一発でgnoteに反映できるようにしたツールです。RPAがボタンを一つずつクリックしていた作業を、指定されたボタンを一発で選択できるようになりました。",
        longDescription: "kintoneの設定内容をGASで一発でgnoteに反映できるようにしたツールです。RPAがボタンを一つずつクリックしていた作業を、指定されたボタンを一発で選択できるようになり、RPAの実行時間が大幅に短縮されました。",
        problem: "kintoneに登録されている設定内容をRPAでgnoteに反映していたが、リスト数が多くRPAの実行時間をかなり使ってしまっていた。RPAがボタンを一つ一つクリックする必要があり、効率が悪かった。",
        features: [
            "kintoneからgnoteへの設定を一発で反映",
            "RPAの実行時間を大幅短縮",
            "コールリスト作成画面とDMリスト作成画面で使用可能",
            "管理画面と表画面のどちらからも操作可能",
        ],
        tags: ["Chrome拡張", "GAS"],
        imageUrl: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?q=80&w=2000&auto=format&fit=crop",
        technologies: ["Chrome拡張機能", "Google Apps Script", "kintone API"],
        featured: false,
        savedHours: 200,
    },
    {
        id: "10",
        title: "gnote入庫管理 設定支援ツール",
        description: "スプレッドシートで設定内容を一元管理し、gnote入庫管理システムの各画面に一括で反映するChrome拡張機能です。大量の項目を一気に反映でき、選択までを自動化し、登録は人間が行う安全設計です。",
        longDescription: "スプレッドシートで設定内容を一元管理し、gnote入庫管理システムの各画面に一括で反映するChrome拡張機能です。大量の項目を一気に反映でき、「現在の値」と「変更後の値」を比較表示。選択までを自動化し、登録は人間が行う安全設計です。",
        problem: "gnote入庫管理システムの設定変更で、1ページでも入力すべき項目が大量にある。さらに店舗が大量にあり、同じ変更を何店舗にも反映しないといけない場合、非常に時間がかかっていた。",
        features: [
            "大量の入力項目を一括で反映",
            "複数店舗への同じ設定変更を一発で反映",
            "変更前後の比較表示で確認しやすい",
            "安全設計：選択は自動、登録は人間が実行",
        ],
        tags: ["Chrome拡張", "GAS"],
        imageUrl: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?q=80&w=2000&auto=format&fit=crop",
        technologies: ["Chrome拡張機能", "Google Apps Script", "Google Sheets"],
        featured: false,
        savedHours: 250,
    },
    {
        id: "11",
        title: "gnote受注管理 設定一括選択ツール",
        description: "コメント雛形やメール通知先などの設定を一発で選択できるようにしたツールです。コールセンター生産チーム向けに、大量の手作業を一発で完了できます。",
        longDescription: "コメント雛形やメール通知先などの設定を一発で選択できるようにしたツールです。基本的には人間が実行ボタンを押す安全設計（一部例外あり、ただし履歴を残しリカバリー可能にしています）。",
        problem: "gnote受注管理システムのコメント雛形やメール通知先の設定で、大量の手作業が発生していた。",
        features: [
            "コメント雛形・メール通知先の一括選択",
            "大量の手作業を一発で完了",
            "安全設計：基本は人間が実行（一部例外は履歴・リカバリー対応）",
            "スプレッドシートでの一元管理",
        ],
        tags: ["Chrome拡張", "GAS"],
        imageUrl: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?q=80&w=2000&auto=format&fit=crop",
        technologies: ["Chrome拡張機能", "Google Apps Script", "Google Sheets"],
        featured: false,
        savedHours: 150,
    },
    {
        id: "12",
        title: "gnote入庫管理 設定一括取得ツール",
        description: "gnote入庫管理システムの設定内容を一括で取得し、現状把握を簡単にするツールです。複数ページを自動で巡回し、全ての設定データをスプレッドシートに一括出力します。",
        longDescription: "gnote入庫管理システムの設定内容を一括で取得し、現状把握を簡単にするツールです。複数ページを自動で巡回し、全ての設定データをスプレッドシートに一括出力。設定変更前の全体像把握が楽になります。",
        problem: "gnote入庫管理システムの設定を変更する際、まず全体像を把握する必要があるが、そのために一覧画面→詳細画面を1件ずつ手動で巡回する必要があり、手作業がかなり多かった。",
        features: [
            "工場一覧・店舗一覧・作業種別一覧を自動巡回",
            "各詳細ページの設定データを自動取得",
            "全設定をスプレッドシートに一括出力",
            "設定変更前の現状把握が簡単に",
        ],
        tags: ["Chrome拡張", "GAS"],
        imageUrl: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?q=80&w=2000&auto=format&fit=crop",
        technologies: ["Chrome拡張機能", "Google Apps Script", "Google Sheets"],
        featured: false,
        savedHours: 100,
    },
    {
        id: "13",
        title: "コールロープレAI訓練システム",
        description: "AIが「顧客役」となってスタッフと会話練習（ロールプレイ）ができるシステムです。マイクで話しかけるとAI顧客が応答し、終了後に「良かった点」「改善点」を自動でフィードバック。",
        longDescription: "AIが「顧客役」となってスタッフと会話練習（ロールプレイ）ができるシステムです。マイクで話しかけるとAI顧客が応答し、終了後に「良かった点」「改善点」を自動でフィードバック。習得するまで何度でも自動で練習できます。",
        problem: "新人採用を毎月行っており、そのための研修も毎月何時間も使っていた。研修担当者の負担が大きく、新人が習得するまで効率的に練習できる環境がなかった。",
        features: [
            "AIとの音声会話による営業練習",
            "5段階の難易度（初心者〜上級者）",
            "80種類以上のシナリオ（様々な顧客タイプ）",
            "AI自動採点（導入トーク、切り返し、クロージング等）",
            "「良かった点」「改善点」の自動フィードバック",
            "スタッフ別の進捗・成績管理",
        ],
        tags: ["LLM（生成AI）", "Webアプリ"],
        imageUrl: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?q=80&w=2000&auto=format&fit=crop",
        technologies: ["Next.js", "OpenAI（Whisper, TTS, GPT）", "kintone"],
        featured: true,
        savedHours: 600,
    },
    {
        id: "14",
        title: "ふるさと納税レビュー収集・分析・返信AI生成",
        description: "複数のECサイトからレビューを自動で収集し、1万件以上のレビューを分析するシステムです。何が良くて何が悪かったのかを可視化し、AIによる返信案の自動生成機能も搭載。",
        longDescription: "複数のECサイトからレビューを自動で収集し、1万件以上のレビューを分析するシステムです。何が良くて何が悪かったのかを可視化し、今後の提案にも活用。悪いレビューにも即座に対応でき、AIによる返信案の自動生成機能も搭載しています。",
        problem: "Amazon、Yahoo!ショッピング、さとふるなど複数のECサイトで約1万件近いページにレビューが散在しており、人力での確認は不可能だった。レビューの存在を把握できず、悪いレビューにも対応できていなかった。",
        features: [
            "Amazon、Yahoo!ショッピング、さとふる等からのレビュー自動取得",
            "1万件以上のレビューを分析・可視化",
            "何が良くて何が悪かったのかを把握、今後の提案にも活用",
            "レビュー内容をAI（ChatGPT）が分析し返信案を自動生成",
            "毎日定時に自動実行（スケジュール設定可能）",
        ],
        tags: ["LLM（生成AI）", "GAS"],
        imageUrl: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?q=80&w=2000&auto=format&fit=crop",
        technologies: ["Google Apps Script", "Playwright", "OpenAI GPT API", "Google Sheets"],
        featured: true,
        impactAmount: 600000,
        impactLabel: "売上（月額5万円）",
    },
    {
        id: "15",
        title: "請求書AIダブルチェック",
        description: "kintoneから請求書PDFを自動取得し、DifyとOpenAIのLLMを使って金額・クライアント名・商品内容などを複数の観点から自動検証するシステムです。",
        longDescription: "kintoneから請求書PDFを自動取得し、Dify（ワークフロー）とOpenAIのLLMを使って金額・クライアント名・商品内容などを複数の観点から自動検証するシステムです。チェック結果（OK/NG）がスプレッドシートに自動記録され、問題があれば即座に把握できます。",
        problem: "請求書PDF/Excelの内容を目視でチェックするのに時間がかかっていた。丁寧に確認してくれていたが、件数が多く負担が大きかった。",
        features: [
            "kintoneから請求書PDF/Excelを自動ダウンロード",
            "AIによる複数観点での自動検証（金額、クライアント名、内容など）",
            "チェック結果をスプレッドシートに自動記録",
            "エラー検出時は再チェック対象として自動マーク",
        ],
        tags: ["LLM（生成AI）", "GAS"],
        imageUrl: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=2000&auto=format&fit=crop",
        technologies: ["Google Apps Script", "Dify（ワークフロー）", "OpenAI LLM", "kintone API", "Google Sheets"],
        featured: true,
        savedHours: 200,
    },
];
